"""create baseline database schema

Revision ID: d59016a14a74
Revises: 
Create Date: 2024-11-19 17:10:42.119729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd59016a14a74'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("aircrafts",
                    sa.Column(name="aircraft_id", type_=sa.Integer, primary_key=True),
                    sa.Column(name="name", type_=sa.String, nullable=False),
                    sa.Column(name="manufacturer", type_=sa.String, nullable=False),
                    sa.Column(name="aircraft_type", type_=sa.String, nullable=True),
                    sa.Column(name="first_flight", type_=sa.String, nullable=True)
                    )

    op.create_table("aircrafts_data",
                    sa.Column(name="aircraft_data_id", type_=sa.Integer, primary_key=True),
                    sa.Column(name="combat_radius", type_=sa.Integer, nullable=True),
                    sa.Column(name="ceiling", type_=sa.Integer, nullable=True),
                    sa.Column(name="weight", type_=sa.Integer, nullable=True),
                    sa.Column(name="armament_weight", type_=sa.Integer, nullable=True),
                    sa.Column(name="take_off_weight", type_=sa.Integer, nullable=True),
                    sa.Column(name="aircraft_id", type_=sa.Integer, nullable=False)
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("aircrafts")
    op.drop_table("aircrafts_data")
    # ### end Alembic commands ###
