"""add column max_speed

Revision ID: ebc5478e47c1
Revises: d59016a14a74
Create Date: 2024-11-19 17:24:59.175885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebc5478e47c1'
down_revision: Union[str, None] = 'd59016a14a74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(table_name='aircrafts_data', column=sa.Column(name='max_speed', type_=sa.Integer, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(table_name='aircrafts_data', column_name='max_speed')
    # ### end Alembic commands ###
